// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

/*
Package pbbackend is a generated protocol buffer package.

It is generated from these files:
	backend.proto

It has these top-level messages:
	Pagination
	Elements
	Element
	ElementID
	Error
*/
package pbbackend

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pagination struct {
	NumberOfItem int32 `protobuf:"varint,1,opt,name=NumberOfItem" json:"NumberOfItem,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pagination) GetNumberOfItem() int32 {
	if m != nil {
		return m.NumberOfItem
	}
	return 0
}

type Elements struct {
	Error   *Error     `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Element []*Element `protobuf:"bytes,2,rep,name=element" json:"element,omitempty"`
}

func (m *Elements) Reset()                    { *m = Elements{} }
func (m *Elements) String() string            { return proto.CompactTextString(m) }
func (*Elements) ProtoMessage()               {}
func (*Elements) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Elements) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Elements) GetElement() []*Element {
	if m != nil {
		return m.Element
	}
	return nil
}

type Element struct {
	Error   *Error     `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	ID      *ElementID `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty"`
	Comment string     `protobuf:"bytes,3,opt,name=comment" json:"comment,omitempty"`
	Body    []byte     `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Owner   string     `protobuf:"bytes,6,opt,name=Owner" json:"Owner,omitempty"`
}

func (m *Element) Reset()                    { *m = Element{} }
func (m *Element) String() string            { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()               {}
func (*Element) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Element) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Element) GetID() *ElementID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Element) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Element) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Element) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ElementID struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ElementID) Reset()                    { *m = ElementID{} }
func (m *ElementID) String() string            { return proto.CompactTextString(m) }
func (*ElementID) ProtoMessage()               {}
func (*ElementID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ElementID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Error struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Pagination)(nil), "pbbackend.Pagination")
	proto.RegisterType((*Elements)(nil), "pbbackend.Elements")
	proto.RegisterType((*Element)(nil), "pbbackend.Element")
	proto.RegisterType((*ElementID)(nil), "pbbackend.ElementID")
	proto.RegisterType((*Error)(nil), "pbbackend.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Backend service

type BackendClient interface {
	Store(ctx context.Context, in *Element, opts ...grpc.CallOption) (*Error, error)
	Fetch(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Element, error)
	List(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*Elements, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) Store(ctx context.Context, in *Element, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := grpc.Invoke(ctx, "/pbbackend.Backend/Store", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Fetch(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Element, error) {
	out := new(Element)
	err := grpc.Invoke(ctx, "/pbbackend.Backend/Fetch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) List(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*Elements, error) {
	out := new(Elements)
	err := grpc.Invoke(ctx, "/pbbackend.Backend/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Backend service

type BackendServer interface {
	Store(context.Context, *Element) (*Error, error)
	Fetch(context.Context, *ElementID) (*Element, error)
	List(context.Context, *Pagination) (*Elements, error)
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Element)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbbackend.Backend/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Store(ctx, req.(*Element))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbbackend.Backend/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Fetch(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbbackend.Backend/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).List(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbbackend.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Backend_Store_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _Backend_Fetch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Backend_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xed, 0xa6, 0xdd, 0xc6, 0x4e, 0xab, 0x94, 0xb1, 0xc2, 0x5a, 0x2f, 0x61, 0x11, 0xc9, 0x41,
	0xaa, 0xb4, 0x7e, 0x81, 0xa4, 0x42, 0x40, 0xac, 0xac, 0x3f, 0x60, 0x92, 0xae, 0x1a, 0x34, 0xd9,
	0xb2, 0x59, 0x11, 0xbf, 0xc5, 0xb3, 0xff, 0x29, 0xdd, 0xa4, 0xb5, 0x92, 0x1c, 0xbc, 0xcd, 0xbc,
	0xf7, 0xe6, 0xcd, 0x9b, 0x64, 0x61, 0x3f, 0x8e, 0x92, 0x57, 0x99, 0x2f, 0x27, 0x2b, 0xad, 0x8c,
	0xc2, 0xde, 0x2a, 0xae, 0x00, 0x7e, 0x09, 0x70, 0x1f, 0x3d, 0xa7, 0x79, 0x64, 0x52, 0x95, 0x23,
	0x87, 0xc1, 0xdd, 0x7b, 0x16, 0x4b, 0xbd, 0x78, 0x0a, 0x8d, 0xcc, 0x18, 0xf1, 0x88, 0x4f, 0xc5,
	0x1f, 0x8c, 0x3f, 0xc2, 0xde, 0xfc, 0x4d, 0x66, 0x32, 0x37, 0x05, 0x9e, 0x01, 0x95, 0x5a, 0x2b,
	0x6d, 0x85, 0xfd, 0xe9, 0x70, 0xb2, 0x35, 0x9e, 0xcc, 0xd7, 0xb8, 0x28, 0x69, 0x3c, 0x07, 0x57,
	0x96, 0x33, 0xcc, 0xf1, 0xda, 0x7e, 0x7f, 0x8a, 0xbb, 0xca, 0x92, 0x11, 0x1b, 0x09, 0xff, 0x22,
	0xe0, 0x56, 0xe0, 0xbf, 0x37, 0x9c, 0x82, 0x13, 0x06, 0xcc, 0xb1, 0xa2, 0x51, 0xdd, 0x3c, 0x0c,
	0x84, 0x13, 0x06, 0xc8, 0xc0, 0x4d, 0x54, 0x66, 0x73, 0xb4, 0x3d, 0xe2, 0xf7, 0xc4, 0xa6, 0x45,
	0x84, 0x4e, 0xac, 0x96, 0x9f, 0x8c, 0x7a, 0xc4, 0x1f, 0x08, 0x5b, 0xe3, 0x08, 0xe8, 0xe2, 0x23,
	0x97, 0x9a, 0x75, 0xad, 0xb6, 0x6c, 0xf8, 0x09, 0xf4, 0xb6, 0xa6, 0x78, 0x60, 0xd7, 0x12, 0xcb,
	0x3b, 0x61, 0xc0, 0x8f, 0x81, 0xda, 0x58, 0x38, 0x84, 0xb6, 0xd4, 0xba, 0x62, 0xd6, 0xe5, 0xf4,
	0x9b, 0x80, 0x7b, 0x5d, 0xa6, 0xc2, 0x0b, 0xa0, 0x0f, 0x46, 0x69, 0x89, 0x0d, 0xdf, 0x61, 0x5c,
	0xbb, 0x91, 0xb7, 0x70, 0x06, 0xf4, 0x46, 0x9a, 0xe4, 0x05, 0x1b, 0x6f, 0x1b, 0x37, 0xd8, 0xf0,
	0x16, 0x5e, 0x41, 0xe7, 0x36, 0x2d, 0x0c, 0x1e, 0xed, 0xb0, 0xbf, 0x3f, 0x7b, 0x7c, 0x58, 0x1f,
	0x2a, 0x78, 0x2b, 0xee, 0xda, 0x37, 0x32, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x12, 0x5e, 0xbf,
	0x98, 0x34, 0x02, 0x00, 0x00,
}
